version: "3.1"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672

  movies:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:8000
    env_file:
      - .env
    command: npm run start
    depends_on:
      - mongo
      - redis
      - rabbitmq

  log:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:8081
    env_file:
      - .env
    command: npm run log
    depends_on:
      - mongo
      - redis
      - rabbitmq
